version: '3'
services:
  web:
    image: yiisoftware/yii2-php:8.1-apache
    working_dir: /app
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - .:/app:delegated
    ports:
      - '8000:80'
    depends_on:
      - db
  db:
    image: mysql
    # container_name: newspapersite-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'user'
      MYSQL_PASS: 'pass'
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    # container_name: newspapersite-phpmyadmin
    ports:
      - '8888:80'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    depends_on:
      - db
  
volumes:
  mysql: